name: Terraform Destroy

on:
  workflow_dispatch:  # Permite ejecución manual desde GitHub Actions

permissions:
  id-token: write
  contents: read

jobs:
  tf-destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7  # Ajusta la versión si es necesario

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Initialize Terraform
        run: terraform init -input=false

      - name: Validate Terraform configuration
        run: terraform validate

      - name: Terraform Destroy
        run: terraform destroy -auto-approve

